pluginManagement {
    repositories {
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.minecraftforge.net/" }
        gradlePluginPortal()
    }
}
rootProject.name = 'miapi'

include("common")
include("fabric")
include("forge")

def enableAddons = providers
        .gradleProperty("run_addons")
        .map { it.toBoolean() }
        .orElse(false)
        .get()

if (enableAddons && System.getenv("JITPACK") == null) {
    includeBuild("./archery")
    includeBuild("./arsenal")
    includeBuild("./armory")
}