pluginManagement {
    repositories {
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.neoforged.net/releases/" }
        maven { url "https://maven.parchmentmc.org" }
        gradlePluginPortal()
    }
}
rootProject.name = 'miapi'

include("common")
include("fabric")
include("neoforge")


def addons = providers
        .gradleProperty("addons")
        .map { it.split(',')*.trim() as Set }
        .orElse([] as Set)
        .get()

if (System.getenv("JITPACK") == null) {
    if (addons.contains("archery")) includeBuild("./archery")
    if (addons.contains("armory")) includeBuild("./armory")
    if (addons.contains("arsenal")) includeBuild("./arsenal")
}