pluginManagement {
    repositories {
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.neoforged.net/releases/" }
        maven { url "https://maven.parchmentmc.org" }
        gradlePluginPortal()
    }
}
rootProject.name = 'miapi'

include("common")
include("fabric")
include("neoforge")

//def enableAddons = settings.hasProperty('run_addons') && settings.property('run_addons') == 'true'


if (true) {
    includeBuild("./archery")
    includeBuild("./armory")
    includeBuild("./arsenal")
}