modLoader="javafml" #mandatory
loaderVersion="${neoforge_loader_version_range}"
license="CC-BY-NC-4.0"
issueTrackerURL="https://github.com/Truly-Modular/Modular-Item-API/issues"
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${version}" #mandatory
displayName="${mod_name}" #mandatory
displayURL="https://truly-modular.github.io/" #optional
logoFile="icon.png" #optional
credits="${credits}" #optional
authors="${mod_author}" #optional
description='''${mod_description}'''
[[mixins]]
config = "miapi.mixins.json"

[[mixins]]
config = "miapi-common.mixins.json"
[[dependencies.${mod_id}]] #optional
   modId="neoforge" #mandatory
   mandatory=true #mandatory
   versionRange="${neoforge_version_range}" #mandatory
   ordering="NONE"
   side="BOTH"
[[dependencies.${mod_id}]] #optional
   modId="nucleus_config" #mandatory
   mandatory=true #mandatory
   versionRange="[1.0.0,)" #mandatory
   ordering="AFTER"
   side="BOTH"
[[dependencies.${mod_id}]] #optional
   modId="architectury" #mandatory
   mandatory=true #mandatory
   versionRange="[${architectury_version},)" #mandatory
   ordering="NONE"
   side="BOTH"
[[dependencies.${mod_id}]]
   modId="minecraft"
   mandatory=true
   versionRange="[${minecraft_version},)"
   ordering="NONE"
   side="BOTH"
